config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get 'club/home_club', as: 'clubs'
  get 'club/new_club'
  post 'club/create_club'
  get 'club/edit_club/:club_id' => 'club#edit_club'
  post 'club/update_club/:club_id' => 'club#update_club'
  post 'club/destroy_club/:club_id' => 'club#destroy_club'
  get 'club/index_club/:club_id' => 'club#index_club'
  get 'clubs/index_club/:club_id/cocomentclubs/create' => 'cocomentclubs#create'
  get 'clubs/index_club/:club_id/cocomentclubs/destroy/:cocomentclubs_id' => 'cocomentclubs#destroy'
  get 'clubs/index_club/:club_id/cocomentclubs/edit/:cocomentclubs_id' =>'cocomentclubs#edit'
  post 'clubs/index_club/:club_id/cocomentclubs/update/:cocomentclubs_id' =>'cocomentclubs#update'
  get 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/create' => 'cococlubs#create'
  get 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/:cococlub_id/destroy' => 'cococlubs#destroy'
  get 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/:cococlub_id/edit' => 'cococlubs#edit'
  post 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/:cococlub_id/update' => 'cococlubs#update'
  
  get 'matching/home_matching', as: 'matchings'
  get 'matching/new_matching'
  post 'matching/create_matching'
  get 'matching/edit_matching/:matching_id' => 'matching#edit_matching'
  post 'matching/update_matching/:matching_id' => 'matching#update_matching'
  post 'matching/destroy_matching/:matching_id' => 'matching#destroy_matching'
  get 'matching/index_matching/:matching_id' => 'matching#index_matching'
  get 'matchings/index_matching/:matching_id/commentmatchings/create' => 'commentmatchings#create'
  get 'matchings/index_matching/:matching_id/commentmatchings/destroy/:commentmatchings_id' => 'commentmatchings#destroy'
  get 'matchings/index_matching/:matching_id/commentmatchings/edit/:commentmatchings_id' =>'commentmatchings#edit'
  post 'matchings/index_matching/:matching_id/commentmatchings/update/:commentmatchings_id' =>'commentmatchings#update'
  get 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/create' => 'cocomatchings#create'
  get 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/:cocomatching_id/edit' => 'cocomatchings#edit'
  post 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/:cocomatching_id/update' => 'cocomatchings#update'
  get 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/:cocomatching_id/destroy' => 'cocomatchings#destroy'
  
  get 'info/home_info', as: 'infos'
  get 'info/new_info'
  post 'info/create_info'
  get 'info/edit_info/:info_id' => 'info#edit_info'
  post 'info/update_info/:info_id' => 'info#update_info'
  post 'info/destroy_info/:info_id' => 'info#destroy_info'
  get 'info/index_info/:info_id' => 'info#index_info'
  get 'infos/index_info/:info_id/commentinfos/create' => 'commentinfos#create'
  get 'infos/index_info/:info_id/commentinfos/destroy/:commentinfos_id' => 'commentinfos#destroy'
  get 'infos/index_info/:info_id/commentinfos/edit/:commentinfos_id' =>'commentinfos#edit'
  post 'infos/index_info/:info_id/commentinfos/update/:commentinfos_id' =>'commentinfos#update'
  get 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/create' => 'cocoinfos#create'
  get 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/:cocoinfo_id/edit' => 'cocoinfos#edit'
  post 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/:cocoinfo_id/update' => 'cocoinfos#update'
  get 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/:cocoinfo_id/destroy' => 'cocoinfos#destroy'

  get 'notice/home_notice'
  get 'notice/new_notice'
  post 'notice/create_notice'
  get 'notice/edit_notice/:notice_id' => 'notice#edit_notice'
  post 'notice/update_notice/:notice_id' => 'notice#update_notice'
  post 'notice/destroy_notice/:notice_id' => 'notice#destroy_notice'
  get 'notice/index_notice/:notice_id' => 'notice#index_notice'
  get 'notices/index_notice/:notice_id/comments/create' => 'comments#create'
  get 'notices/index_notice/:notice_id/comments/destroy/:comments_id' => 'comments#destroy'
  get 'notices/index_notice/:notice_id/comments/edit/:comments_id' =>'comments#edit'
  post 'notices/index_notice/:notice_id/comments/update/:comments_id' =>'comments#update'
  get 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/create' => 'coconotices#create'
  get 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/:coconotice_id/edit' => 'coconotices#edit'
  post 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/:coconotice_id/update' => 'coconotices#update'
  get 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/:coconotice_id/destroy' => 'coconotices#destroy'
  
  get 'page/edit_page'
  get 'page/create_page'
  get 'page/home_page'
  get 'page/save_page'
  
  get 'review/home_review', as: 'reviews'
  get 'review/new_review'
  post 'review/create_review'
  get 'review/index_review/:review_id' => 'review#index_review'
  get 'review/edit_review/:review_id' => 'review#edit_review'
  post 'review/update_review/:review_id' => 'review#update_review'
  post 'review/destroy_review/:review_id' => 'review#destroy_review'
  get 'reviews/index_review/:review_id/coreviews/create' => 'coreviews#create'
  get 'reviews/index_review/:review_id/coreviews/destroy/:coreviews_id' => 'coreviews#destroy'
  get 'reviews/index_review/:review_id/coreviews/edit/:coreviews_id' =>'coreviews#edit'
  post 'reviews/index_review/:review_id/coreviews/update/:coreviews_id' =>'coreviews#update'
  get 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/create' => 'cocoreviews#create'
  get 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/:cocoreview_id/edit' => 'cocoreviews#edit'
  post 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/:cocoreview_id/update' => 'cocoreviews#update'
  get 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/:cocoreview_id/destroy' => 'cocoreviews#destroy'
  
  get 'question/home_question', as: 'questions'
  get 'question/new_question'
  post 'question/create_question'
  get 'question/edit_question/:question_id' => 'question#edit_question'
  post 'question/update_question/:question_id' => 'question#update_question'
  post 'question/destroy_question/:question_id' => 'question#destroy_question'
  get 'question/index_question/:question_id' => 'question#index_question'
  get 'questions/index_question/:question_id/commentquestions/create' => 'commentquestions#create'
  get 'questions/index_question/:question_id/commentquestions/destroy/:commentquestions_id' => 'commentquestions#destroy'
  get 'questions/index_question/:question_id/commentquestions/edit/:commentquestions_id' =>'commentquestions#edit'
  post 'questions/index_question/:question_id/commentquestions/update/:commentquestions_id' =>'commentquestions#update'
  get 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/create' => 'cocoquestions#create'
  get 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/:cocoquestion_id/edit' => 'cocoquestions#edit'
  post 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/:cocoquestion_id/update' => 'cocoquestions#update'
  get 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/:cocoquestion_id/destroy' => 'cocoquestions#destroy'
  
  root 'main#index_main'
  get 'main/index_main'
  
  get 'friendlist/friendlistindex'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/matching.rb
class Matching < ApplicationRecord
    
    resourcify
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :commentmatchings, :dependent => :destroy
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
 load_and_authorize_resource
  before_action :set_matching, only: [:index_matching, :edit_matching, :update_matching, :destroy_matching]
  before_action :authenticate_user!, except: [:home_matching]
 
  
  def home_matching
    @q = Matching.ransack(params[:q])
    @matchings = @q.result(distict: true)
    @matchings= Matching.all
  end

  def index_matching
    @commentmatchings = @matching.commentmatchings
  end


  def new_matching
     @matching = Matching.new
  end

  def create_matching
     
    @matching = Matching.new(matching_params)
    @matching.user_id = current_user.id
   
    if @matching.save
    else
    end
     
     redirect_to '/matching/home_matching'
  end

  def edit_matching

  end

  def update_matching
    @matching.update(matching_params)
    if @matching.save
    else
    end
    
     redirect_to :controller => 'matching', :action => 'index_matching'
  end

  def destroy_matching
    @matching.destroy

    redirect_to '/matching/home_matching'
  end
  
  
  private
  
  def matching_params
    params.require(:matching).permit(:title, :content, :user_id, :image, :check)
  end
  
  def set_matching
      @matching = Matching.find(params[:matching_id])
  end
  
  def form_for
    @matching=Matching.new
  end
  
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/views/matching/create_matching.html.erb
<h1>Matching#create_matching</h1>
<p>Find me in app/views/matching/create_matching.html.erb</p>

app/views/matching/destroy_matching.html.erb
<h1>Matching#destroy_matching</h1>
<p>Find me in app/views/matching/destroy_matching.html.erb</p>

app/views/matching/edit_matching.html.erb
<br/>
<div class="box">
<h3>Edit your post</h3>

<form action="/matching/update_matching/<%= @matching.id %>/" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  Title : <input type="text" name="matching[title]" value="<%= @matching.title %>"><br />
  Content : <textarea name="matching[content]" rows="8" cols="80"><%=  @matching.content%></textarea><br />
  Condition (Open or Done) : <input type="text" name="matching[check]" value="<%= @matching.check%>"><br />
  <span class="image right"><input type="submit" value="Submit"></span>
</form>
<br/><br/>
</div>

app/views/matching/home_matching.html.erb
<!DOCTYPE html>
<br/>
<h1>Matching Groups</h1>
<blockquote>
한국 학생들과 외국에서 온 교환학생들이 원하는 목표의 소모임을 만드는 공간입니다! 
<br/>
인원과 소모임목적은 모두 자유이고, 댓글을 통해 자유롭게 팀멤버 신청을 하여 소모임을 만들어 활동하면 됩니다. 
<br/><br/>
It is a space for Korean students and exchange students from abroad to make free gatherings! 
<br/>
You freely make gatherings and also can apply for team members through comments.
</blockquote>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Content</th>
    <th>Time</th>
    <th>Condition</th>
  </tr>

<tr>
    <% @matchings.each do |p|%>
    <td><%=p.user.name%></td>
    <td>
      <% if p.title.empty? %>
      <a href="/matching/index_matching/<%=p.id%>"> No Title </a>
      <% else %>
      <a href="/matching/index_matching/<%=p.id%>"> <%= p.title%> </a>
      <% end %>
    </td>
    <td><%= p.content %></td>
    <td><%= p.created_at.strftime("%Y-%m-%d %H:%M") %></td>
    <td><%= p.check %></td>
  </tr>
  <% end %>
</table>

<span class="image right"><a href="/matching/new_matching" class="button primary">Write New Post</a></span>
<br /><br /><br />


</html>

app/views/matching/index_matching.html.erb
<!DOCTYPE html>
<html>
    <style>


.bubble{
    background-color: #F2F2F2;
    border-radius: 5px;
    box-shadow: 0 0 6px #B2B2B2;
    display: inline-block;
    padding: 10px 18px;
    position: relative;
    vertical-align: top;
        float: left;   
    margin: 5px 45px 5px 20px;   
}

.bubble::before {
    background-color: #F2F2F2;
    content: "\00a0";
    display: block;
    height: 16px;
    position: absolute;
    top: 11px;
    transform:             rotate( 29deg ) skew( -35deg );
        -moz-transform:    rotate( 29deg ) skew( -35deg );
        -ms-transform:     rotate( 29deg ) skew( -35deg );
        -o-transform:      rotate( 29deg ) skew( -35deg );
        -webkit-transform: rotate( 29deg ) skew( -35deg );
    width:  20px;
     box-shadow: -2px 2px 2px 0 rgba( 178, 178, 178, .4 );
    left: -9px;  
}


    </style>

<section>
<div class="table-wrapper">

  <table>
								<thead>
				  <tr>
					  <th>Title: <%= @matching.title %></th>
                      <th>Time : <%= @matching.created_at.strftime("%Y-%m-%d %H:%M") %> </th>
                      <th>User: <%=@matching.user.name %> </th>
                      <th>Condition: <%=@matching.check %></th>
                  </tr>
  </table>
                  
   <%= @matching.content %><br/>
   <%= image_tag("#{@matching.image}") %>
</div>

<br /><br /><br />

<div>  
   
   <% if can? :edit_matching, @matching %>
     <span class="image left">
       <button><a href="/matching/edit_matching/<%= @matching.id %>">Edit Post</a></button>
     </span>
   <% end %>
   
       <% if can? :destroy_matching, @matching %>
        <form action="/matching/destroy_matching/<%= @matching.id %>" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <span class="image left">
        <input type="submit" name="" value="Delete Post">
        </form>
        </span>
  </br></br>
        <%end%>
</div>
  <br />
  
  <span class= "image right">
      <a href='/matching/home_matching' class = "button primary small"> Back to the list </a>
  </span>  
  <br/><br/>
  <hr>
	<h2>Comments</h2>	
  
<% @commentmatchings.each do |comment| %>

<div class= "commentbox"> 
  <p><b><%= comment.user.name %></b></p> 
  <p><%= comment.content %></p>
  <!--추가-->
  <p><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></p>

  
  <span class= "image right">
    <ul>
      <% if can? :destroy, comment %>
      <a href="/matchings/index_matching/<%=@matching.id%>/commentmatchings/destroy/<%= comment.id %>" data-confirm='댓글을 삭제합니다.'>Delete </a>
      <%end%>
    
      <% if can? :edit, comment %>
        <a href="/matchings/index_matching/<%= @matching.id %>/commentmatchings/edit/<%= comment.id %>" data-confirm='댓글을 수정합니다.'> Edit </a> 
      <%end%>
    </ul>
  </span>
 
  
  <% comment.cocomatchings.each do |p| %>
       <div class="bubble">
       <b><%= p.user.name %> :  </b>
       <b><%= p.content %></b> </br>
       <%= p.created_at.strftime("%Y-%m-%d %H:%M") %>
       </div>
       </br></br>
     <% if can? :destroy, p %>
     <a href='/matchings/index_matching/<%= @matching.id%>/commentmatchings/<%=comment.id%>/cocomatchings/<%=p.id%>/edit'> 댓글 수정</a>
     <%end%>
      
     <% if can? :edit, p %>
     <a href='/matchings/index_matching/<%= @matching.id%>/commentmatchings/<%=comment.id%>/cocomatchings/<%=p.id%>/destroy'>댓글 삭제</a>
     <%end%>
     </br></br>
  <%end%>
     <form action="/matchings/index_matching/<%= @matching.id%>/commentmatchings/<%=comment.id%>/cocomatchings/create" method='get'>
    <input type='text' name='input_comment'>
    <input type='submit' value='RE: '>
    </form>
  
  </div>
   
<% end %>

<br/>
<form action="/matchings/index_matching/<%= @matching.id %>/commentmatchings/create" method='get'>
    <ul class="actions">
  <input type='text' name='input_comment'><input type='submit' value='Write Comment'>
   </ul>
  </form>
</section>
  
  </html>
  
  
 

 

app/views/matching/new_matching.html.erb
<br/>
<div class= "box">

<h3>New Post</h3>
<br/>
<%= form_for(@matching, url: matching_create_matching_path) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div><br>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div><br>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
  </div><br>
  <div class="field">
    <label>Condition (Open or Done)</label>
    <%= f.text_field :check %>
  </div>
  
  <br><br>
  <span class="image right">
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

 </span>
<br/><br/>
</div>

app/views/matching/update_matching.html.erb
<h1>Matching#update_matching</h1>
<p>Find me in app/views/matching/update_matching.html.erb</p>