config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get 'club/home_club', as: 'clubs'
  get 'club/new_club'
  post 'club/create_club'
  get 'club/edit_club/:club_id' => 'club#edit_club'
  post 'club/update_club/:club_id' => 'club#update_club'
  post 'club/destroy_club/:club_id' => 'club#destroy_club'
  get 'club/index_club/:club_id' => 'club#index_club'
  get 'clubs/index_club/:club_id/cocomentclubs/create' => 'cocomentclubs#create'
  get 'clubs/index_club/:club_id/cocomentclubs/destroy/:cocomentclubs_id' => 'cocomentclubs#destroy'
  get 'clubs/index_club/:club_id/cocomentclubs/edit/:cocomentclubs_id' =>'cocomentclubs#edit'
  post 'clubs/index_club/:club_id/cocomentclubs/update/:cocomentclubs_id' =>'cocomentclubs#update'
  get 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/create' => 'cococlubs#create'
  get 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/:cococlub_id/destroy' => 'cococlubs#destroy'
  get 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/:cococlub_id/edit' => 'cococlubs#edit'
  post 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/:cococlub_id/update' => 'cococlubs#update'
  
  get 'matching/home_matching', as: 'matchings'
  get 'matching/new_matching'
  post 'matching/create_matching'
  get 'matching/edit_matching/:matching_id' => 'matching#edit_matching'
  post 'matching/update_matching/:matching_id' => 'matching#update_matching'
  post 'matching/destroy_matching/:matching_id' => 'matching#destroy_matching'
  get 'matching/index_matching/:matching_id' => 'matching#index_matching'
  get 'matchings/index_matching/:matching_id/commentmatchings/create' => 'commentmatchings#create'
  get 'matchings/index_matching/:matching_id/commentmatchings/destroy/:commentmatchings_id' => 'commentmatchings#destroy'
  get 'matchings/index_matching/:matching_id/commentmatchings/edit/:commentmatchings_id' =>'commentmatchings#edit'
  post 'matchings/index_matching/:matching_id/commentmatchings/update/:commentmatchings_id' =>'commentmatchings#update'
  get 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/create' => 'cocomatchings#create'
  get 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/:cocomatching_id/edit' => 'cocomatchings#edit'
  post 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/:cocomatching_id/update' => 'cocomatchings#update'
  get 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/:cocomatching_id/destroy' => 'cocomatchings#destroy'
  
  get 'info/home_info', as: 'infos'
  get 'info/new_info'
  post 'info/create_info'
  get 'info/edit_info/:info_id' => 'info#edit_info'
  post 'info/update_info/:info_id' => 'info#update_info'
  post 'info/destroy_info/:info_id' => 'info#destroy_info'
  get 'info/index_info/:info_id' => 'info#index_info'
  get 'infos/index_info/:info_id/commentinfos/create' => 'commentinfos#create'
  get 'infos/index_info/:info_id/commentinfos/destroy/:commentinfos_id' => 'commentinfos#destroy'
  get 'infos/index_info/:info_id/commentinfos/edit/:commentinfos_id' =>'commentinfos#edit'
  post 'infos/index_info/:info_id/commentinfos/update/:commentinfos_id' =>'commentinfos#update'
  get 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/create' => 'cocoinfos#create'
  get 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/:cocoinfo_id/edit' => 'cocoinfos#edit'
  post 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/:cocoinfo_id/update' => 'cocoinfos#update'
  get 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/:cocoinfo_id/destroy' => 'cocoinfos#destroy'

  get 'notice/home_notice'
  get 'notice/new_notice'
  post 'notice/create_notice'
  get 'notice/edit_notice/:notice_id' => 'notice#edit_notice'
  post 'notice/update_notice/:notice_id' => 'notice#update_notice'
  post 'notice/destroy_notice/:notice_id' => 'notice#destroy_notice'
  get 'notice/index_notice/:notice_id' => 'notice#index_notice'
  get 'notices/index_notice/:notice_id/comments/create' => 'comments#create'
  get 'notices/index_notice/:notice_id/comments/destroy/:comments_id' => 'comments#destroy'
  get 'notices/index_notice/:notice_id/comments/edit/:comments_id' =>'comments#edit'
  post 'notices/index_notice/:notice_id/comments/update/:comments_id' =>'comments#update'
  get 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/create' => 'coconotices#create'
  get 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/:coconotice_id/edit' => 'coconotices#edit'
  post 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/:coconotice_id/update' => 'coconotices#update'
  get 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/:coconotice_id/destroy' => 'coconotices#destroy'
  
  get 'page/edit_page'
  get 'page/create_page'
  get 'page/home_page'
  get 'page/save_page'
  
  get 'review/home_review', as: 'reviews'
  get 'review/new_review'
  post 'review/create_review'
  get 'review/index_review/:review_id' => 'review#index_review'
  get 'review/edit_review/:review_id' => 'review#edit_review'
  post 'review/update_review/:review_id' => 'review#update_review'
  post 'review/destroy_review/:review_id' => 'review#destroy_review'
  get 'reviews/index_review/:review_id/coreviews/create' => 'coreviews#create'
  get 'reviews/index_review/:review_id/coreviews/destroy/:coreviews_id' => 'coreviews#destroy'
  get 'reviews/index_review/:review_id/coreviews/edit/:coreviews_id' =>'coreviews#edit'
  post 'reviews/index_review/:review_id/coreviews/update/:coreviews_id' =>'coreviews#update'
  get 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/create' => 'cocoreviews#create'
  get 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/:cocoreview_id/edit' => 'cocoreviews#edit'
  post 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/:cocoreview_id/update' => 'cocoreviews#update'
  get 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/:cocoreview_id/destroy' => 'cocoreviews#destroy'
  
  get 'question/home_question', as: 'questions'
  get 'question/new_question'
  post 'question/create_question'
  get 'question/edit_question/:question_id' => 'question#edit_question'
  post 'question/update_question/:question_id' => 'question#update_question'
  post 'question/destroy_question/:question_id' => 'question#destroy_question'
  get 'question/index_question/:question_id' => 'question#index_question'
  get 'questions/index_question/:question_id/commentquestions/create' => 'commentquestions#create'
  get 'questions/index_question/:question_id/commentquestions/destroy/:commentquestions_id' => 'commentquestions#destroy'
  get 'questions/index_question/:question_id/commentquestions/edit/:commentquestions_id' =>'commentquestions#edit'
  post 'questions/index_question/:question_id/commentquestions/update/:commentquestions_id' =>'commentquestions#update'
  get 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/create' => 'cocoquestions#create'
  get 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/:cocoquestion_id/edit' => 'cocoquestions#edit'
  post 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/:cocoquestion_id/update' => 'cocoquestions#update'
  get 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/:cocoquestion_id/destroy' => 'cocoquestions#destroy'
  
  root 'main#index_main'
  get 'main/index_main'
  
  get 'friendlist/friendlistindex'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    resourcify
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :commentquestions, :dependent => :destroy 
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  
  load_and_authorize_resource
  before_action :set_question, only: [:index_question, :edit_question, :update_question, :destroy_question]
  before_action :authenticate_user!, except: [:home_question]
 
  
  def home_question
    @q = Question.ransack(params[:q])
    @questions = @q.result(distict: true)
    @questions= Question.all
  end

  def index_question
    @commentquestions = @question.commentquestions
  end


  def new_question
     @question = Question.new
  end

  def create_question
     
    @question = Question.new(question_params)
    @question.user_id= current_user.id
   
    if @question.save
    else
    end
     
     redirect_to '/question/home_question'
  end

  def edit_question

  end

  def update_question
    @question.update(question_params)
    if @question.save
    else
    end
    
     redirect_to :controller => 'question', :action => 'index_question'
  end

  def destroy_question
    @question.destroy

    redirect_to '/question/home_question'
  end
  
  
  private
  
  def question_params
    params.require(:question).permit(:title, :content, :user_id, :image)
  end
  
  def set_question
    @question = Question.find(params[:question_id])
  end
  
  def form_for
    @question=Question.new
  end
  
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/question/create_question.html.erb
<h1>Question#create_question</h1>
<p>Find me in app/views/question/create_question.html.erb</p>

app/views/question/destroy_question.html.erb
<h1>Question#destroy_question</h1>
<p>Find me in app/views/question/destroy_question.html.erb</p>

app/views/question/edit_question.html.erb
<br/>
<div class="box">
<h3>Edit your post</h3>
<form action="/question/update_question/<%= @question.id %>/" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  Title : <input type="text" name="question[title]" value="<%= @question.title %>"><br />
  Content : <textarea name="question[content]" rows="8" cols="80"><%=  @question.content%></textarea><br />
  <span class="image right"><input type="submit" value="Submit"></span>
</form>
<br/><br/>
</div>

app/views/question/home_question.html.erb
<!DOCTYPE html>
<html>
<br/>
<h1>FAQ </h1>
<blockquote>
외국으로 교환학생을 가려는 한국학생들이 자유롭게 질문을 올리는 게시판입니다. <br/><br/>
This is a bulletin board where Korean students can ask questions. </blockquote>

<table>
 <table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Content</th>
    <th>Time</th>
  </tr>
  
<tr>
    <% @questions.each do |p|%>
    <td><%=p.user.name%></td>
    <td><a href="/question/index_question/<%=p.id%>"><%=p.title%></a> </td>
    <td><%= p.content %></td>
    <td><%= p.created_at.strftime("%Y-%m-%d %H:%M") %></td>
  </tr>
  <% end %>
</table>
<br>



<span class="image right"><a href="/question/new_question" class="button primary">Write New Post</a></span>
<br /><br /><br />

</html>

app/views/question/index_question.html.erb
<!DOCTYPE html>
<html>
    <style>


.bubble{
    background-color: #F2F2F2;
    border-radius: 5px;
    box-shadow: 0 0 6px #B2B2B2;
    display: inline-block;
    padding: 10px 18px;
    position: relative;
    vertical-align: top;
        float: left;   
    margin: 5px 45px 5px 20px;   
}

.bubble::before {
    background-color: #F2F2F2;
    content: "\00a0";
    display: block;
    height: 16px;
    position: absolute;
    top: 11px;
    transform:             rotate( 29deg ) skew( -35deg );
        -moz-transform:    rotate( 29deg ) skew( -35deg );
        -ms-transform:     rotate( 29deg ) skew( -35deg );
        -o-transform:      rotate( 29deg ) skew( -35deg );
        -webkit-transform: rotate( 29deg ) skew( -35deg );
    width:  20px;
     box-shadow: -2px 2px 2px 0 rgba( 178, 178, 178, .4 );
    left: -9px;  
}


    </style>
<section>
<div class="table-wrapper">

  <table>
								<thead>
								  <tr>
								      <th>Title: <%= @question.title %></th>
                      <th>Time : <%= @question.created_at.strftime("%Y-%m-%d %H:%M") %> </th>
                      <th>User: <%=@question.user.name %> </th>
                  </tr>
                  </table>
                  
   <%= @question.content %><br/>
   <%= image_tag("#{@question.image}") %>
</div>

<br /><br /><br />
<div>  
   <% if can? :edit_question, @question %>
    <span class="image left"><button><a href=""/question/edit_question/<%= @question.id %>">Edit Post</a></button></span>
  <% end %>
  
   <% if can? :destroy_question, @question %>
    <form action="/question/destroy_question/<%= @question.id %>" method="post">
     <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
     <span class="image left">
   <input type="submit" name="" value="Delete Post">
    </form>
    </span>
  </br></br>
  <%end%>
  </div>
  
  <br />
  <span class= "image right"><a href='/question/home_question' class = "button primary small"> Back to the list </a></span>  
  <br/><br/>
  <hr>
	<h2>Comments</h2>			
  
  
  <% @commentquestions.each do |comment| %>
  <div class= "commentbox"> 
  <p><b><%= comment.user.name %></b></p> 
  <p><%= comment.content %></p>
  <!--추가-->
  <p><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></p>

  
  <span class= "image right">
  <ul>
  <% if can? :destroy, comment %>
  <a href="/questions/index_question/<%=@question.id%>/commentquestions/destroy/<%= comment.id %>" data-confirm='댓글을 삭제합니다.'> Delete </a>
  <%end%>
  
  <% if can? :edit, comment %>
  <a href="/questions/index_question/<%= @question.id %>/commentquestions/edit/<%= comment.id %>" data-confirm='댓글을 수정합니다.'> Edit </a> 
  <%end%>
  </ul>
  </span>
  
  
  <% comment.cocoquestions.each do |p| %>
    <div class="bubble">
       <b><%= p.user.name %> :  </b>
       <b><%= p.content %></b> </br>
       <%= p.created_at.strftime("%Y-%m-%d %H:%M") %>
       </div>
       </br></br>
      <% if can? :destroy, p %>
     <a href='/questions/index_question/<%= @question.id%>/commentquestions/<%=comment.id%>/cocoquestions/<%=p.id%>/edit'> 댓글 수정</a>
     <%end%>
      
      <% if can? :edit, p %>
     <a href='/questions/index_question/<%= @question.id%>/commentquestions/<%=comment.id%>/cocoquestions/<%=p.id%>/destroy'>댓글 삭제</a>
     <%end%>
     </br></br>
  <%end%>
    <form action="/questions/index_question/<%= @question.id%>/commentquestions/<%=comment.id%>/cocoquestions/create" method='get'>
    <input type='text' name='input_comment'>
    <input type='submit' value='댓글 작성'>
    </form>
  
  </div>
  
  
<% end %>  
 
<br/>
<form action="/questions/index_question/<%= @question.id %>/commentquestions/create" method='get'>
    <ul class="actions">
  <input type='text' name='input_comment'><input type='submit' value='Submit'>
   </ul>
  </form>
  
</section>



 
  </br></br>
  
  

app/views/question/new_question.html.erb
<br/>
<div class= "box">

<h3>New Post</h3>
<br/>
<%= form_for(@question, url: question_create_question_path) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
  </div>
  <br/>
  <span class="image right">
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 </span>
<br/><br/>
</div>

app/views/question/update_question.html.erb
<h1>Question#update_question</h1>
<p>Find me in app/views/question/update_question.html.erb</p>