config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get 'club/home_club', as: 'clubs'
  get 'club/new_club'
  post 'club/create_club'
  get 'club/edit_club/:club_id' => 'club#edit_club'
  post 'club/update_club/:club_id' => 'club#update_club'
  post 'club/destroy_club/:club_id' => 'club#destroy_club'
  get 'club/index_club/:club_id' => 'club#index_club'
  get 'clubs/index_club/:club_id/cocomentclubs/create' => 'cocomentclubs#create'
  get 'clubs/index_club/:club_id/cocomentclubs/destroy/:cocomentclubs_id' => 'cocomentclubs#destroy'
  get 'clubs/index_club/:club_id/cocomentclubs/edit/:cocomentclubs_id' =>'cocomentclubs#edit'
  post 'clubs/index_club/:club_id/cocomentclubs/update/:cocomentclubs_id' =>'cocomentclubs#update'
  get 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/create' => 'cococlubs#create'
  get 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/:cococlub_id/destroy' => 'cococlubs#destroy'
  get 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/:cococlub_id/edit' => 'cococlubs#edit'
  post 'clubs/index_club/:club_id/cocomentclubs/:cocomentclub_id/cococlubs/:cococlub_id/update' => 'cococlubs#update'
  
  get 'matching/home_matching', as: 'matchings'
  get 'matching/new_matching'
  post 'matching/create_matching'
  get 'matching/edit_matching/:matching_id' => 'matching#edit_matching'
  post 'matching/update_matching/:matching_id' => 'matching#update_matching'
  post 'matching/destroy_matching/:matching_id' => 'matching#destroy_matching'
  get 'matching/index_matching/:matching_id' => 'matching#index_matching'
  get 'matchings/index_matching/:matching_id/commentmatchings/create' => 'commentmatchings#create'
  get 'matchings/index_matching/:matching_id/commentmatchings/destroy/:commentmatchings_id' => 'commentmatchings#destroy'
  get 'matchings/index_matching/:matching_id/commentmatchings/edit/:commentmatchings_id' =>'commentmatchings#edit'
  post 'matchings/index_matching/:matching_id/commentmatchings/update/:commentmatchings_id' =>'commentmatchings#update'
  get 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/create' => 'cocomatchings#create'
  get 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/:cocomatching_id/edit' => 'cocomatchings#edit'
  post 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/:cocomatching_id/update' => 'cocomatchings#update'
  get 'matchings/index_matching/:matching_id/commentmatchings/:commentmatching_id/cocomatchings/:cocomatching_id/destroy' => 'cocomatchings#destroy'
  
  get 'info/home_info', as: 'infos'
  get 'info/new_info'
  post 'info/create_info'
  get 'info/edit_info/:info_id' => 'info#edit_info'
  post 'info/update_info/:info_id' => 'info#update_info'
  post 'info/destroy_info/:info_id' => 'info#destroy_info'
  get 'info/index_info/:info_id' => 'info#index_info'
  get 'infos/index_info/:info_id/commentinfos/create' => 'commentinfos#create'
  get 'infos/index_info/:info_id/commentinfos/destroy/:commentinfos_id' => 'commentinfos#destroy'
  get 'infos/index_info/:info_id/commentinfos/edit/:commentinfos_id' =>'commentinfos#edit'
  post 'infos/index_info/:info_id/commentinfos/update/:commentinfos_id' =>'commentinfos#update'
  get 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/create' => 'cocoinfos#create'
  get 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/:cocoinfo_id/edit' => 'cocoinfos#edit'
  post 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/:cocoinfo_id/update' => 'cocoinfos#update'
  get 'infos/index_info/:info_id/commentinfos/:commentinfo_id/cocoinfos/:cocoinfo_id/destroy' => 'cocoinfos#destroy'

  get 'notice/home_notice'
  get 'notice/new_notice'
  post 'notice/create_notice'
  get 'notice/edit_notice/:notice_id' => 'notice#edit_notice'
  post 'notice/update_notice/:notice_id' => 'notice#update_notice'
  post 'notice/destroy_notice/:notice_id' => 'notice#destroy_notice'
  get 'notice/index_notice/:notice_id' => 'notice#index_notice'
  get 'notices/index_notice/:notice_id/comments/create' => 'comments#create'
  get 'notices/index_notice/:notice_id/comments/destroy/:comments_id' => 'comments#destroy'
  get 'notices/index_notice/:notice_id/comments/edit/:comments_id' =>'comments#edit'
  post 'notices/index_notice/:notice_id/comments/update/:comments_id' =>'comments#update'
  get 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/create' => 'coconotices#create'
  get 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/:coconotice_id/edit' => 'coconotices#edit'
  post 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/:coconotice_id/update' => 'coconotices#update'
  get 'notices/index_notice/:notice_id/comments/:comment_id/coconotices/:coconotice_id/destroy' => 'coconotices#destroy'
  
  get 'page/edit_page'
  get 'page/create_page'
  get 'page/home_page'
  get 'page/save_page'
  
  get 'review/home_review', as: 'reviews'
  get 'review/new_review'
  post 'review/create_review'
  get 'review/index_review/:review_id' => 'review#index_review'
  get 'review/edit_review/:review_id' => 'review#edit_review'
  post 'review/update_review/:review_id' => 'review#update_review'
  post 'review/destroy_review/:review_id' => 'review#destroy_review'
  get 'reviews/index_review/:review_id/coreviews/create' => 'coreviews#create'
  get 'reviews/index_review/:review_id/coreviews/destroy/:coreviews_id' => 'coreviews#destroy'
  get 'reviews/index_review/:review_id/coreviews/edit/:coreviews_id' =>'coreviews#edit'
  post 'reviews/index_review/:review_id/coreviews/update/:coreviews_id' =>'coreviews#update'
  get 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/create' => 'cocoreviews#create'
  get 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/:cocoreview_id/edit' => 'cocoreviews#edit'
  post 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/:cocoreview_id/update' => 'cocoreviews#update'
  get 'reviews/index_review/:review_id/coreviews/:coreview_id/cocoreviews/:cocoreview_id/destroy' => 'cocoreviews#destroy'
  
  get 'question/home_question', as: 'questions'
  get 'question/new_question'
  post 'question/create_question'
  get 'question/edit_question/:question_id' => 'question#edit_question'
  post 'question/update_question/:question_id' => 'question#update_question'
  post 'question/destroy_question/:question_id' => 'question#destroy_question'
  get 'question/index_question/:question_id' => 'question#index_question'
  get 'questions/index_question/:question_id/commentquestions/create' => 'commentquestions#create'
  get 'questions/index_question/:question_id/commentquestions/destroy/:commentquestions_id' => 'commentquestions#destroy'
  get 'questions/index_question/:question_id/commentquestions/edit/:commentquestions_id' =>'commentquestions#edit'
  post 'questions/index_question/:question_id/commentquestions/update/:commentquestions_id' =>'commentquestions#update'
  get 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/create' => 'cocoquestions#create'
  get 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/:cocoquestion_id/edit' => 'cocoquestions#edit'
  post 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/:cocoquestion_id/update' => 'cocoquestions#update'
  get 'questions/index_question/:question_id/commentquestions/:commentquestion_id/cocoquestions/:cocoquestion_id/destroy' => 'cocoquestions#destroy'
  
  root 'main#index_main'
  get 'main/index_main'
  
  get 'friendlist/friendlistindex'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/info.rb
class Info < ApplicationRecord
    resourcify
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many:commentinfos, :dependent=>:destroy
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  load_and_authorize_resource
  before_action :set_info, only: [:index_info, :edit_info, :update_info, :destroy_info]
  before_action :authenticate_user!, except: [:home_info]
 
  
  def home_info
    @q = Info.ransack(params[:q])
    @infos = @q.result(distict: true)
    @infos= Info.all
  end

  def index_info
    @commentinfos = @info.commentinfos
  end


  def new_info
     @info = Info.new
  end

  def create_info
     
    @info = Info.new(info_params)
    @info.user_id= current_user.id
   
    if @info.save
    else
    end
     
     redirect_to '/info/home_info'
  end

  def edit_info

  end

  def update_info
    @info.update(info_params)
    if @info.save
    else
    end
    
     redirect_to :controller => 'info', :action => 'index_info'
  end

  def destroy_info
    @info.destroy

    redirect_to '/info/home_info'
  end
  
  
  private
  
  def info_params
    params.require(:info).permit(:title, :content, :user_id, :image)
  end
  
  def set_info
    @info = Info.find(params[:info_id])
  end
  
  def form_for
    @info =Info.new
  end
end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/create_info.html.erb
<h1>Info#create_info</h1>
<p>Find me in app/views/info/create_info.html.erb</p>

app/views/info/destroy_info.html.erb
<h1>Info#destroy_info</h1>
<p>Find me in app/views/info/destroy_info.html.erb</p>

app/views/info/edit_info.html.erb
<br/>
<div class="box">
<h3>Edit your post</h3>
<form action="/info/update_info/<%= @info.id %>/" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  Title : <input type="text" name="info[title]" value="<%= @info.title %>"><br />
  Content : <textarea name="info[content]" rows="8" cols="80"><%=  @info.content%></textarea><br />
  <span class="image right"><input type="submit" value="Submit"></span>
</form>
<br/><br/>
</div>

app/views/info/home_info.html.erb
<!DOCTYPE html>
<html>
<br/>
<h1>Share Information</h1>
<blockquote>
교환학생에 관련된 기본적인 정보들을 공유하는 곳입니다! 한국에서 생활하는 외국인 학생들이 불편한점이나 궁금한점을 공유할 수 있도록 만든 게시판 입니다! 
<br/>Share necessary information! This bulletin board allows foreign students living in Korea to share their inconveniences or questions!</blockquote>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Content</th>
    <th>Time</th>
  </tr>
  
  <tr>
    <% @infos.each do |p|%>
    <td><%=p.user.name%></td>
    <td><a href="/info/index_info/<%= p.id %>"> <%= p.title%> </a> </td>
    <td><%= p.content %></td>
    <td><%= p.created_at.strftime("%Y-%m-%d %H:%M") %></td>
  </tr>
  <% end %>
</table>


<span class="image right"><a href="/info/new_info" class="button primary">Write New Post</a></span>
<br /><br /><br />

</html>

app/views/info/index_info.html.erb
<!DOCTYPE html>
<html>
    <style>


.bubble{
    background-color: #F2F2F2;
    border-radius: 5px;
    box-shadow: 0 0 6px #B2B2B2;
    display: inline-block;
    padding: 10px 18px;
    position: relative;
    vertical-align: top;
        float: left;   
    margin: 5px 45px 5px 20px;   
}

.bubble::before {
    background-color: #F2F2F2;
    content: "\00a0";
    display: block;
    height: 16px;
    position: absolute;
    top: 11px;
    transform:             rotate( 29deg ) skew( -35deg );
        -moz-transform:    rotate( 29deg ) skew( -35deg );
        -ms-transform:     rotate( 29deg ) skew( -35deg );
        -o-transform:      rotate( 29deg ) skew( -35deg );
        -webkit-transform: rotate( 29deg ) skew( -35deg );
    width:  20px;
     box-shadow: -2px 2px 2px 0 rgba( 178, 178, 178, .4 );
    left: -9px;  
}


    </style>

  <section>
<div class="table-wrapper">

  <table>
								<thead>
								  <tr>
								      <th>Title: <%= @info.title %></th>
                      <th>Time : <%=@info.created_at.strftime("%Y-%m-%d %H:%M") %> </th>
                      <th>User: <%=@info.user.name %> </th>
                  </tr>
                  </table>
                  
   <%= @info.content %><br/>
   <%= image_tag("#{@info.image}") %>
</div>

<br /><br /><br />
<div>
  <% if can? :edit_info, @info %>
  <span class="image left"><button><a href="/info/edit_info/<%= @info.id %>">Edit Post</a></button></span>
  <% end %>
   
  
  <% if can? :destroy_info, @info %>
    <form action="/info/destroy_info/<%= @info.id %>" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
   <span class="image left">
   <input type="submit" name="" value="Delete Post">
    </form>
    </span>
  </br></br>
  <%end%>
  </div>
  
  <br />
  <span class= "image right"><a href='/question/home_question' class = "button primary small"> Back to the list </a></span>  
  <br/><br/>
  <hr>
	<h2>Comments</h2>			
	
<% @commentinfos.each do |comment| %>
	<div class= "commentbox"> 
  <p><b><%= comment.user.name %></b></p> 

  <p><%= comment.content %></p>
  
  <!--추가-->
  <p><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></p>

  <span class= "image right">
  <ul>
	<% if can? :destroy, comment %>
    <a href='/infos/index_info/<%= @info.id %>/commentinfos/destroy/<%= comment.id %>’ data-confirm=' data-confirm='댓글을 삭제합니다.'> Delete </a>
  <%end%>
    <% if can? :edit, comment %>
    <a href="/infos/index_info/<%= @info.id %>/commentinfos/edit/<%= comment.id %>" data-confirm='댓글을 수정합니다.'> Edit </a> 
  <%end%>
  </ul>
  </span>
  
  
  <% comment.cocoinfos.each do |p| %>
     <div class="bubble">
       <b><%= p.user.name %> :  </b>
       <b><%= p.content %></b> </br>
       <%= p.created_at.strftime("%Y-%m-%d %H:%M") %>
       </div>
       </br></br>
       <% if can? :edit, p %>
     <a href='/infos/index_info/<%= @info.id%>/commentinfos/<%=comment.id%>/cocoinfos/<%=p.id%>/edit'> 댓글 수정</a>
     <%end%>
      
       <% if can? :destroy, p %>
     <a href='/infos/index_info/<%= @info.id%>/commentinfos/<%=comment.id%>/cocoinfos/<%=p.id%>/destroy'>댓글 삭제</a>
     <%end%>
     </br></br>
  <%end%>
  
  
  <form action="/infos/index_info/<%= @info.id%>/commentinfos/<%=comment.id%>/cocoinfos/create" method='get'>
    <input type='text' name='input_comment'>
    <input type='submit' value='댓글 작성'>
    </form>
  
  </div>
  

  
<% end %>  
 
<br/>
<form action="/infos/index_info/<%= @info.id%>/commentinfos/create" method='get'>
    <ul class="actions">
  <input type='text' name='input_comment'><input type='submit' value='Submit'>
   </ul>
  </form>
  
</section>



 
	
	

</html>

app/views/info/new_info.html.erb
<br/>
<div class= "box">

<h3>New Post</h3>
<br/>
<%= form_for(@info, url: info_create_info_path) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
  </div>
  <br/>
  <span class="image right">
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 </span>
<br/><br/>
</div>

app/views/info/update_info.html.erb
<h1>Info#update_info</h1>
<p>Find me in app/views/info/update_info.html.erb</p>